# Generated by Django 3.0.8 on 2020-08-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_question_has_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_choices',
            field=models.BooleanField(default=False, verbose_name='Has choices'),
            preserve_default=False,
        ),
    ]
