# Generated by Django 3.0.8 on 2020-08-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_has_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='has_choices',
        ),
    ]
